org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

maven_group=io.github.u2894638479
archives_base_name=KotlinMCUI-backend
license=MIT
mod_version=1.0.0-alpha.18
mod_id=kotlinmcuibackend
mod_name=KotlinMCUI-backend
mod_description=backend for kotlinmcui
mod_authors=2894638479
mod_github=https://github.com/2894638479/KotlinMCUI-backend
mod_issues=https://github.com/2894638479/KotlinMCUI-backend/issues
mod_mcmod=
mod_modrinth=https://modrinth.com/project/FjVgWB2Y
mod_curseforge=https://legacy.curseforge.com/minecraft/mc-mods/kotlinmcui-backend
icon=assets/kotlinmcuibackend/icon.png

kotlin_version=2.4.0
java_version=21

kotlinmcui_version=1.0.0-alpha.32

minecraft_version=1.21.1
minecraft_version_range=1.21.1

loader=neoforge
loader_suffix=kff
# https://github.com/NeoForgeMDKs
plugin_version=2.0.140
loader_version=21.1.219
loader_version_range=[1,)

kff_version=5.12.0